### ISSUE TITLE
epochs_create.py raises TypeError (python 3.8.10, nk 0.2.2)

### ISSUE THREAD

**Issue by frenzels** [neuropsychology/NeuroKit#764]
Hi,
I encountered the following error when playing around with some of the example code: epochs_create.py raises a type error ("data type 'string' not understood"). The error can be reproduced by the following example code:

ecg = nk.ecg_simulate(duration=30, sampling_rate=300, noise=0.2)
ecg_cleaned = nk.ecg_clean(ecg, sampling_rate=300)
quality = nk.ecg_quality(ecg_cleaned, sampling_rate=300)

It seems it can be fixed by replacing:

epochs_create.py, line 215: epochs[i][colname] = epochs[i][colname].astype("string")

with

epochs_create.py, line 215: epochs[i][colname] = epochs[i][colname].astype("str")

Best,
Stefan

-----------------------------------------------------------------------------------------------------------------------------------------------------
**Output**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/neurokit2/ecg/ecg_quality.py", line 103, in ecg_quality
    quality = _ecg_quality_averageQRS(ecg_cleaned, rpeaks=rpeaks, sampling_rate=sampling_rate)
  File "/home/user/.local/lib/python3.8/site-packages/neurokit2/ecg/ecg_quality.py", line 133, in _ecg_quality_averageQRS
    heartbeats = ecg_segment(ecg_cleaned, rpeaks, sampling_rate)
  File "/home/user/.local/lib/python3.8/site-packages/neurokit2/ecg/ecg_segment.py", line 54, in ecg_segment
    heartbeats = epochs_create(
  File "/home/user/.local/lib/python3.8/site-packages/neurokit2/epochs/epochs_create.py", line 215, in epochs_create
    epochs[i][colname] = epochs[i][colname].astype("str")
  File "/usr/lib/python3/dist-packages/pandas/core/generic.py", line 5881, in astype
    new_data = self._data.astype(
  File "/usr/lib/python3/dist-packages/pandas/core/internals/managers.py", line 581, in astype
    return self.apply("astype", dtype=dtype, **kwargs)
  File "/usr/lib/python3/dist-packages/pandas/core/internals/managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/lib/python3/dist-packages/pandas/core/internals/blocks.py", line 559, in astype
    return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)
  File "/usr/lib/python3/dist-packages/pandas/core/internals/blocks.py", line 614, in _astype
    dtype = pandas_dtype(dtype)
  File "/usr/lib/python3/dist-packages/pandas/core/dtypes/common.py", line 2055, in pandas_dtype
    raise TypeError("data type '{}' not understood".format(dtype))
TypeError: data type 'string' not understood

**System Specifications**

Ubuntu focal fossa with python 3.8.10 

nk.version()
- OS: Linux (ELF 64bit) 
- Python: 3.8.10 
- NeuroKit2: 0.2.2 

- NumPy: 1.17.4 
- Pandas: 0.25.3 
- SciPy: 1.3.3 
- sklearn: 1.2.0 
- matplotlib: 3.1.2

**Comment by DominiqueMakowski** [comment]
Would you like to open a small PR to make the fix? :)
